const GET_DATA = 'GET_DATA';
const GET_ID = 'GET_ID';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const FILTER = "FILTER";
const ORDER = "ORDER";


module.exports = {
    GET_DATA, GET_ID, GET_ACTIVITIES, SEARCH_COUNTRY, NEXT_PAGE, PREV_PAGE, FILTER, ORDER, 
};