const GET_DATA = 'GET_DATA';
const GET_ID = 'GET_ID';
const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
const NEXT_PAGE = "NEXT_PAGE";
const PREV_PAGE = "PREV_PAGE";
const FILTER = "FILTER";
const ORDER = "ORDER";
const POPULATION = "POPULATION"
const RESTORE_ORIGINAL_COUNTRIES = "RESTORE_ORIGINAL_COUNTRIES"
const CREATE_ACTIVITY = "CREATE_ACTIVITY";
const FILTERACT = "FILTERACT"
const FETCH_ACTIVITIES = "FETCH_ACTIVITIES"

module.exports = {
    GET_DATA, GET_ID, SEARCH_COUNTRY, NEXT_PAGE, PREV_PAGE, FILTER, ORDER, POPULATION, RESTORE_ORIGINAL_COUNTRIES, CREATE_ACTIVITY,  FETCH_ACTIVITIES, FILTERACT
};