const GET_DATA = 'GET_DATA';
const GET_ID = 'GET_ID';
const GET_ACTIVITIES = 'GET_ACTIVITIES';
const SEARCH_COUNTRY = 'SEARCH_COUNTRY'



module.exports = {
    GET_DATA, GET_ID, GET_ACTIVITIES, SEARCH_COUNTRY
};